titre: 1er Hackathon des applications citoyennes
slug: hackathon-novembre-2026
description: Toutes les infos se trouvent sur [cette page](https://reconnexion.coop/nous-rencontrer/hackathon-nov-2026)
image: /images/1790238121775.jpeg
debut: 2026-11-26T09:00
fin: 2026-11-27T17:00
journee_entiere: false
format: presentiel
lien_visio: https://meet.reconnexion.coop/zww-ygql-jes
adresse: La Filature, 10 Rue du Pérou, 69100 Villeurbanne
recurrence: aucune
fin_recurrence: ''
dates_annulees: []
