titre: Applications maléables
slug: applications-maleables
type: solutions
couleur: '#008020'
accroche: Je peux choisir des applications qui collent parfaitement à mes besoins
essentiel: Dans le monde actuel, les utilisateurs ont tendance à adapter leurs comportements ou habitudes aux applications qu’ils utilisent. Mais avec l’avénement de l’IA, on peut imaginer que des applications soient conçues « sur mesure » aux besoins d’un utilisateur
licence: CC-BY-SA
