titre: Application anti-sociales
slug: application-anti-sociales
type: fleaux
couleur: '#f00020'
accroche: Des applications qui isolent les gens et détruisent la société
essentiel: Une étude « Capitalisme de la solitude » ont montré que les GAFAM ont tout intérêt à créer de la solitude, car cela augmente le temps passé sur son écran.
licence: CC-BY-SA
