titre: Cimetière d’applications vertueuses
slug: cimetiere-dapplications-vertueuses
type: fleaux
couleur: '#f00020'
accroche: Des centaines d’applications utiles qui ne décollent jamais
licence: CC-BY-SA
