titre: Liberté de changer d’application
slug: liberte-de-changer-dapplication
type: solutions
couleur: '#008020'
accroche: Si une application ne me convient plus, je peux passer facilement à une alternative
licence: CC-BY-SA
