# Sections ajoutées en bas de chaque page d'application (/applications/<slug>), sous les discussions du forum.
sections_bas:
  - type: annonce
    titre: Newsletter
    texte: Suivez l'actualité et recevez les invitations aux temps forts.
    bouton_texte: M'abonner à la Newsletter
    bouton_lien: https://b144bca4.sibforms.com/serve/MUIFAMvMggADvfUsaaPvIeGfL_OR2_ub7mDxgo197al-8br9KKpRQ6fsnnyxEXSFJS-CTI0iB6G3Skf1tAsOCzHbQ_0ei08gm_a0nWTOAfq5lXCV1UWNXytGDdli7g09YW8kcnXqZeL5uROxSnsO1XSLzKTeplhqZJECpxmKaJ_Nslpf6GColxZWrAiwwJO1wbUnfGCoQFkTvi93
